Repository openfun/fun-richie-site-factory, pull requests merged in 2023-10, with the labels that each got.

#131 ✨(ademe) add redirect for OpenEdX course urls
  .circleci/config.yml
  sites/ademe/CHANGELOG.md
  sites/ademe/src/backend/ademe/urls.py
  sites/ademe/src/backend/base/tests/test_views.py
  sites/ademe/src/backend/base/urls.py
  sites/ademe/src/backend/base/views.py
Labels: improvement

#132 🍱(ademe) add a custom favicon
  sites/ademe/CHANGELOG.md
  sites/ademe/src/backend/base/static/richie/favicon/favicon.ico
  sites/ademe/src/backend/templates/richie/base.html
Labels: feature

#139 🛂(all) update default course and organization permissions
  .circleci/config.yml
  sites/ademe/CHANGELOG.md
  sites/ademe/src/backend/ademe/settings.py
  sites/ademe/src/backend/base/migrations/0001_initial.py
  sites/ademe/src/backend/base/migrations/__init__.py
  sites/funcampus/CHANGELOG.md
  sites/funcampus/src/backend/base/migrations/0001_initial.py
  sites/funcampus/src/backend/base/migrations/__init__.py
  sites/funcampus/src/backend/funcampus/settings.py
  sites/funcorporate/CHANGELOG.md
  sites/funcorporate/src/backend/base/migrations/0001_initial.py
  sites/funcorporate/src/backend/base/migrations/__init__.py
  sites/funcorporate/src/backend/funcorporate/settings.py
  sites/funmooc/CHANGELOG.md
  sites/funmooc/src/backend/base/migrations/0001_initial.py
  sites/funmooc/src/backend/base/migrations/__init__.py
  sites/funmooc/src/backend/funmooc/settings.py
Labels: bug, FUN

#140 ✨(ademe) setup tarteaucitron
  .circleci/config.yml
  sites/ademe/CHANGELOG.md
  sites/ademe/src/backend/ademe/settings.py
  sites/ademe/src/backend/base/context_processors.py
  sites/ademe/src/backend/base/tests/test_template.py
  sites/ademe/src/backend/templates/richie/base.html
  sites/ademe/src/frontend/scss/_main.scss
  sites/ademe/src/frontend/scss/components/libs/_tarteaucitron.scss
  sites/ademe/src/frontend/scss/extras/colors/_theme.scss
Labels: feature

#142 🍱(ademe) add PWA icons
  sites/ademe/CHANGELOG.md
  sites/ademe/src/backend/base/static/richie/favicon/android-chrome-192x192.png
  sites/ademe/src/backend/base/static/richie/favicon/android-chrome-512x512.png
  sites/ademe/src/backend/base/static/richie/favicon/apple-touch-icon.png
  sites/ademe/src/backend/base/static/richie/favicon/browserconfig.xml
  sites/ademe/src/backend/base/static/richie/favicon/favicon-16x16.png
  sites/ademe/src/backend/base/static/richie/favicon/favicon-32x32.png
  sites/ademe/src/backend/base/static/richie/favicon/mstile-150x150.png
  sites/ademe/src/backend/base/static/richie/favicon/site.webmanifest
  sites/ademe/src/backend/templates/richie/base.html
Labels: feature

#141 💄(ademe) fix background color of active pagination item
  sites/ademe/CHANGELOG.md
  sites/ademe/src/frontend/scss/extras/colors/_theme.scss
Labels: improvement
