Repository openfun/fun-richie-site-factory, pull requests merged in 2024-04, with the labels that each got.

#173 🍱 (ademe) change logo
  .circleci/config.yml
  sites/ademe/CHANGELOG.md
  sites/ademe/src/backend/base/static/richie/images/logo-alt.png
  sites/ademe/src/backend/base/static/richie/images/logo.png
  sites/ademe/src/frontend/scss/components/_header.scss
  sites/ademe/src/frontend/scss/extras/settings/_variables.scss
Labels: feature request

#181 🔧(funmooc) add settings API_TOKEN for JOANIE_BACKEND
  .circleci/config.yml
  sites/funmooc/CHANGELOG.md
  sites/funmooc/src/backend/funmooc/settings.py
Labels: FUN

#189 🚑(funmooc) fix malformed dashboard url
  .circleci/config.yml
  sites/funmooc/CHANGELOG.md
  sites/funmooc/src/backend/funmooc/settings.py
Labels: bug, critical
